name: Builds
run-name: ${{ github.actor }} runs Gitea Actions
on: [push]

jobs:
  ExectOS WebSite:
    runs-on: oscw
    container:
      image: codingworkshop/oscw-runner:latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build WebSite
        run: hugo
      - name: Publish WebSite
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          OSCW_ARTIFACTS_HOSTNAME: ${{ secrets.OSCW_ARTIFACTS_HOSTNAME }}
          OSCW_ARTIFACTS_USERNAME: ${{ secrets.OSCW_ARTIFACTS_USERNAME }}
          OSCW_ARTIFACTS_USERKEY: ${{ secrets.OSCW_ARTIFACTS_USERKEY }}
        run: webpage_publish public/ 1e8c78e4764c760b3d20991c8b769cf5
